#!/bin/bash
export REPORT_FOLDER="reports"
export PMD_CONFIG_URL_APEX="https://raw.githubusercontent.com/Ko-Sit/salesforce-code-review/main/pmd-config.xml"
export PMD_CONFIG_APEX="$RULES_FOLDER/apex-rules.xml"
export PMD_CONFIG_URL_JS="https://raw.githubusercontent.com/Ko-Sit/salesforce-code-review/main/pmd-ruleset-js.xml"
export PMD_CONFIG_JS="$RULES_FOLDER/js-rules.xml"
export PMD_CONFIG_URL_VF="https://raw.githubusercontent.com/Ko-Sit/salesforce-code-review/main/pmd-ruleset-vf.xml"
export PMD_CONFIG_VF="$RULES_FOLDER/vf-rules.xml"
export TARGET_SOURCE="${TARGET_SOURCE:=force-app}"
export TARGET_SOURCE_CPD="force-app/main/default/classes/service"
