image:
  name: atlassian/default-image:2

definitions:
  steps:
    - step: &code-analysis
        name: Code Analysis
        image: ksdocker1001/sfdxscanner:1.2
        caches:
          - node
        artifacts:
          - reports/**
        script:
          - /bin/bash ./scanner-compile.sh
pipelines:
  pull-requests:
    "**":
      - step:
          <<: *code-analysis
  custom:
    sfdx-scanner:
      - step:
          <<: *code-analysis
